### ISSUE TITLE
Install fails on node version 18?

### ISSUE THREAD

**Issue by lukethacoder** [salesforce/sa11y#356]
Is there a reason the packages are flagged at `^14 || ^16`?

Node 14 EOL is in April, and node 16 EOL is later this year in October. [ref](https://github.com/nodejs/Release)

**Comment by navateja-alagam** [comment]
The node version was flagged as `^14 || ^16` from what it was earlier as `^14` was just to have the CI pipeline(circleCI & github-actions) execute for both versions.

There's no install failure issues on node version 18 and we shall update the package to consider using ^18 before the EOL dates and other packages starts picking up the update. Entered [W-12472133](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001KSWXyYAP/view) in the backlog to track this

**Comment by lukethacoder** [comment]
![image](https://user-images.githubusercontent.com/13529535/216133462-aef07605-ffdd-4402-a1b7-f4ab989d5038.png)

Attempting to install using v18 does fail. Keen to see the package updated to include node v18
