### ISSUE TITLE
build: improve versioning workflow

### ISSUE THREAD

**Issue by mohanraj-r** [salesforce/sa11y#40]
Current workflow is to bump versions whenever there a package changes from master (using `"lint:version": "vertioner && yarn lerna exec --since master vertioner"`)

@trevor-bliss [pointed out couple of issues with this approach](https://github.com/salesforce/sa11y/pull/39#r494670179):
> 1. There can be version conflicts between PRs. Imagine there are several PRs open at the same time and they all bump the version to the next patch version. As soon as one gets merged, all other PRs must go in and bump their version again. This potentially repeats for every open PR when a different PR is merged. 
>
> 2. There may be versions in github without corresponding NPM releases. Unless we release every commit to master to NPM, there may be several version bumps before a new version in NPM. Not necessarily a bad thing but can be confusing IMO.
>
> 3. We put the burden of versioning on the PR author. When I contribute to other projects I just focus on the code fix rather than worrying about whether something should be a patch vs. minor release. 
>
> Just my opinion but I think it makes more sense to leave the versions untouched in PRs and then do a release from `master` or a release branch and we as project maintainers decide when that release happens and what version to bump to.

Look into alternate solutions that resolves these issues.

**Comment by mohanraj-r** [comment]
@trevor-bliss I have been meaning to look at [atlassian/changesets: 🦋 A way to manage your versioning and changelogs with a focus on monorepos](https://github.com/atlassian/changesets)
Looks like it might address the issues you pointed out? ([the bot](https://github.com/apps/changeset-bot) looks cool)
Have you come across anything similar? Do you think this is worth looking into?

**Comment by jasonschroeder-sfdc** [comment]
We're going with option 2 via #227
