### ISSUE TITLE
import { assertAccessible, assertAccessibleSync } problem

### ISSUE THREAD

**Issue by testing-blaze** [salesforce/sa11y#45]
**Error**
The test runs fine when not using @sa11y but once its been added as imprt, below error comes up

import { assertAccessible, assertAccessibleSync } from '@sa11y/wdio';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:872:18)

**Package.js**
{
  "name": "accessiblity_testing",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@sa11y/jest": "^0.1.5-beta.0",
    "@sa11y/wdio": "^0.1.2-alpha.0",
    "@wdio/cli": "^6.7.4",
    "@wdio/firefox-profile-service": "^6.6.0",
    "@wdio/local-runner": "^6.7.3",
    "@wdio/mocha-framework": "^6.7.3",
    "@wdio/spec-reporter": "^6.7.0",
    "@wdio/sync": "^6.7.3",
    "chromedriver": "^87.0.0",
    "wdio-chromedriver-service": "^6.0.4"
  },
  "dependencies": {
    "bufferutil": "^4.0.2",
    "utf-8-validate": "^5.0.3"
  }
}

**Test case**
import { assertAccessible, assertAccessibleSync } from '@sa11y/wdio';

const LoginPage = require('../pageobjects/login.page');
const SecurePage = require('../pageobjects/secure.page');

describe('My Login application', () => {
    it('should login with valid credentials', () => {
        LoginPage.open();

        LoginPage.login('tomsmith', 'SuperSecretPassword!');
        assertAccessible();
    });
});

**Comment by mohanraj-r** [comment]
`import` statement requires ES6+ Javascript support in your project.

I see from your sample code that you are using CommonJS `require`. If this is what is configured for your project and working, you can use the same `require` to import `@sa11y/wdio` modules as well.

```js
const { assertAccessible } = require('@sa11y/wdio'); 
```

**Comment by testing-blaze** [comment]
@mohanraj-r Thank you and it worked. However, i have couple of questions
1- The idea is to get on the home page and assert if it meets the accessibility criteria. The test is passing the assertion however there is a very long stack trace generated containing lots of information during the run. I am confused that if the tests is passing then does it mean its all good or we need to look into the stack trace anyways?
2- should this testing done for each individual element or for whole page? Any suggestions?

**Comment by mohanraj-r** [comment]
Please let me know if this is still an issue. Closing for now.

**Comment by mohanraj-r** [comment]
@testing-blaze Sorry didn't notice your latest comment (stale browser tab). 

1. Can you please share the stack trace so I can take a look.
2. Individual element vs whole page depends on your needs. Currently the wdio API doesn't support testing individual elements. There is a PR in progress to add that (#35). But you can use the @sa11y/jest api to test for individual element if you have Jest unit tests.

**Comment by testing-blaze** [comment]
Sharing chunk in below snippet:
```
 }, {
      id: 'svg-non-empty-title',
      evaluate: 'svg-non-empty-title-evaluate'
    }, {
      id: 'caption-faked',
      evaluate: 'caption-faked-evaluate'
    }, {
      id: 'html5-scope',
      evaluate: 'html5-scope-evaluate'
    }, {
      id: 'same-caption-summary',
      evaluate: 'same-caption-summary-evaluate'
    }, {
      id: 'scope-value',
      evaluate: 'scope-value-evaluate',
      options: {
        values: [ 'row', 'col', 'rowgroup', 'colgroup' ]
      }
    }, {
      id: 'td-has-header',
      evaluate: 'td-has-header-evaluate'
    }, {
      id: 'td-headers-attr',
      evaluate: 'td-headers-attr-evaluate'
    }, {
      id: 'th-has-data-cells',
      evaluate: 'th-has-data-cells-evaluate'
    }, {
      id: 'hidden-content',
      evaluate: 'hidden-content-evaluate'
    } ]
  });
})(typeof window === "object" ? window : this);", <object>)
[0-0] 2020-11-17T16:41:32.759Z INFO devtools: COMMAND deleteSession()
[0-0] 2020-11-17T16:41:32.761Z INFO devtools: RESULT null
[0-0] 2020-11-17T16:41:32.764Z INFO devtools: COMMAND executeScript("return (() => {
            return typeof axe === 'object' ? axe.version : undefined;
        }).apply(null, arguments)", <object>)
[0-0] PASSED in chrome - /test/specs/example.e2e.js
2020-11-17T16:41:32.879Z INFO @wdio/cli:launcher: Run onComplete hook

```

**Comment by mohanraj-r** [comment]
Can you try modifying the wdio log-level to `error` and see if that helps
https://webdriver.io/docs/options.html#loglevel

**Comment by testing-blaze** [comment]
@mohanraj-r Thanks. Just to reconfirm does the passing of this test after the assertion tells that all the accessibility guidelines are met by this page?

**Comment by mohanraj-r** [comment]
Yes, a11y issues would result in an error thrown which would cause the test to fail. Test passing without an exception would mean that there are no a11y issues. 

But automation cannot catch all a11y issues - it can check for most WCAG Level A and some AA, AAA rules. As the footer at the results of [axe-cli](https://github.com/dequelabs/axe-core-npm/tree/develop/packages/cli) states
```
Please note that only 20% to 50% of all accessibility issues can automatically be detected.
Manual testing is always required. 
```

**Comment by mohanraj-r** [comment]
@testing-blaze Hope this has answered your questions.
