### ISSUE TITLE
fix(jest): codecov, automatic check tests to work with Jest v27

### ISSUE THREAD

**Issue by mohanraj-r** [salesforce/sa11y#65]
Upgrading from Jest v26 to v27 results in test failures from automatic check tests that exercise the custom hook. Investigate and fix. (Found in #62)

```
 ● automatic checks registration › should run when called directly without setup

    Hooks cannot be defined inside tests. Hook of type "afterEach" is nested within "should run when called directly without setup".

    > 68 |         afterEach(async () => {
         |         ^
      69 |             await automaticCheck(opts);
      70 |         });
      71 |     }

      at eventHandler (node_modules/jest-circus/build/eventHandler.js:107:11)
      at registerSa11yAutomaticChecks (packages/jest/src/automatic.ts:68:9)
      at Object.<anonymous> (packages/jest/__tests__/automatic.test.ts:37:9)
```

**Comment by mohanraj-r** [comment]
Workaround: 
- Use `testRunner: 'jest-jasmine2'` in jest config as mentioned in [Jest 27: New Defaults for Jest, 2021 edition](https://jestjs.io/blog/2021/05/25/jest-27)
- Will use this workaround for now 
  - but jasmine2 test runner will be removed in next major Jest release
  - hence this needs to be fixed before then

**Comment by mohanraj-r** [comment]
Noticing also that codecov is incorrectly reported as missing in certain areas even with `testRunner: 'jest-jasmine2'`. Don't see any updates to istanbul with v27 or any ref to codecov related changes in [Jest 27 Milestone · GitHub](https://github.com/facebook/jest/milestone/12?closed=1). Not sure what could be causing it. Reverting back to v26 for now.

**Comment by mohanraj-r** [comment]
After testing with recent changes in master (#62), the codecov issue is gone. The automatic checks hook still needs to be fixed. Jasmine is configured as the test runner as a workaround for now. The automatic checks fix could be related to or part of #66

**Comment by mohanraj-r** [comment]
Also noticing that the missing codecov reports are inconsistent between 
1. the jest console reporter and the HTML lcov-report
2. subsequent runs - After adding `/* istanbul ignore next */` to reported missing lines, subsequent run errors with missing codecov in different lines that were not previously reported. 

Will test again with future releases of Jest to check if this issue gets fixed.

**Comment by jasonschroeder-sfdc** [comment]
https://github.com/salesforce/sa11y/pull/163
